// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"go-zero-demo/order-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/:id",
				Handler: GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: CreateOrderHandler(serverCtx),
			},
		},
	)
}
