// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Code  int32  `json:"code"`
	Msg   string `json:"msg"`
	Token string `json:"token"`
}

type UserReq struct {
	Name string `path:"name"`
}

type UserResp struct {
	Message string `json:"message"`
}
