// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CommonResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type CreateOrderReq struct {
	Goods_id   int32  `json:"goods_id"`
	Goods_name string `json:"goods_name"`
	Price      int32  `json:"price"`
	Created_at int32  `json:"created_at"`
}

type GetOrderReq struct {
	Id int32 `path:"id"`
}
